name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy==1.17.4
  - scipy==1.3.3
  - matplotlib==3.1.2
  - python=3
  - lfpy
  - ipywidgets==7.5.1
  - bqplot==0.12.5
  - pip
  - pip:
    - opencv-python==4.2.0.32
    - pickle
