name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Cython
  - h5py
  - gxx_linux-64
  - python=3
  - neuron=*=mpi_*
  - lfpy
  - ipywidgets
  - bqplot
  - pip3
  - pip3:
    - opencv-python==4.2.0.32
    - math
    - pickle
